name: Landing Page CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'landing-page/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'landing-page/**' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: landing-page/package-lock.json
      
      - name: Install dependencies
        run: cd landing-page && npm ci
      
      - name: Build landing page
        run: cd landing-page && npm run build
      
      - name: Run tests
        run: cd landing-page && npm test -- --watchAll=false
      
      # Uncomment and configure for actual deployment
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.ORG_ID }}
      #     vercel-project-id: ${{ secrets.PROJECT_ID }}
      #     working-directory: ./landing-page
